version: "3.8"
services:
  db:
    image: postgres:16
    container_name: boardbox_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: boardbox
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5433:5433"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      retries: 20

  catalog:
    build: .
    container_name: boardbox_catalog
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://db:5433/boardbox
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5433/boardbox
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_APPLICATION_NAME: catalog-svc
    ports:
      - "8081:8081"

volumes:
  db_data:
