server {
  listen 80;
  server_name _;

  resolver 127.0.0.11 ipv6=off valid=30s;

  root /usr/share/nginx/html;
  index index.html;

  location /api/catalog/ {
    set $catalog_upstream http://catalog:8081;
    proxy_pass $catalog_upstream;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
  }

  location /api/reservations/ {
    set $reservation_upstream http://reservation:8082;
    proxy_pass $reservation_upstream;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
  }

  location /api/orders {
    set $order_upstream http://order:8083;
    proxy_pass $order_upstream;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
  }

  location /api/users {
    set $order_upstream http://order:8083;
    proxy_pass $order_upstream;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
